language: generic
os: osx
osx_image: xcode8.1
branches:
  only:
  - master
before_install:
- export XCODEBUILD_PATH=$(which xcodebuild)
- export PATH=$PATH:$XCODEBUILD_PATH
- export PATH=$PATH:~/bin
- mkdir ~/go
- export GOPATH=~/go
- brew update
- brew install carthage
- gem install xcpretty --user-install -n~/bin
install:
- xcrun simctl list
- carthage update --platform 'iOS' 
- go get github.com/jwfriese/iossimulator
script:
- go build script/test.go
- ./test 'iOS 10.0' 'iPhone 6'
